[book]
title = "mevlog-rs docs"
src = "src"

[build]
build-dir = "../docs_html"

[output.html]
site-url = "/docs/"
default-theme = "ayu"
preferred-dark-theme = "ayu"
theme = "theme"
additional-css = ["theme/mevlog.css"]
git-repository-url = "https://github.com/pawurb/mevlog-rs"
edit-url-template = "https://github.com/pawurb/mevlog-rs/edit/main/crates/mevlog-backend/docs_src/{path}"
