use crate::content::Faq;

pub struct DocPage {
    pub path: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub breadcrumb_label: &'static str,
    pub last_updated_at: &'static str,
    pub sitemap_priority: &'static str,
    pub sitemap_changefreq: &'static str,
    pub faqs: &'static [Faq],
}

pub const DOC_PAGES: &[DocPage] = &[
    DocPage {
        path: "/docs/",
        title: "mevlog | EVM Transaction Monitoring & Querying CLI",
        description: "mevlog is an EVM transaction monitoring and querying CLI. It detects MEV, tracks smart contract storage, and resolves ENS names across any EVM-compatible chain.",
        breadcrumb_label: "Introduction",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.9",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/quick-start",
        title: "Quick Start | mevlog",
        description: "Run your first mevlog query and index a block range.",
        breadcrumb_label: "Quick Start",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/core-concepts",
        title: "Core Concepts | mevlog",
        description: "The index -> store -> query pipeline, the signatures DB vs the per-chain transactions DB, and how chains are selected.",
        breadcrumb_label: "Core concepts",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/indexing",
        title: "Indexing | mevlog",
        description: "Commands that control how mevlog caches RPC data into the local SQLite database: implicit indexing plus index, reindex, and purge-db.",
        breadcrumb_label: "Indexing",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/schema",
        title: "Database Schema | mevlog",
        description: "The per-chain transactions DB schema: the transactions, blocks, and logs tables and their column types.",
        breadcrumb_label: "Schema",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/evm-sqlite-helpers",
        title: "Functions & Macros | mevlog",
        description: "Custom SQLite functions for U256 BLOB columns (u256_sum, u256_mul, u256_add, u256_to_dec, erc20_to_real), the format_ether/format_gwei/convert_usd/format_usd display helpers, and the {LATEST_BLOCK()}, {NATIVE_TOKEN_PRICE()}, {RESOLVE_ENS()} macros.",
        breadcrumb_label: "Functions & Macros",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/custom-tables",
        title: "Custom Tables | mevlog",
        description: "Define your own tables in ~/.mevlog/config.toml, populated from indexed logs matching a topic0, and query them alongside the built-in tables.",
        breadcrumb_label: "Custom Tables",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/sqlite-storage",
        title: "Storage Requirements | mevlog",
        description: "How the local transactions DB grows as you index, rough mainnet sizing, and checking usage with db-info.",
        breadcrumb_label: "Storage Requirements",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/evm-commands",
        title: "EVM Tracing Commands | mevlog",
        description: "Per-transaction EVM analysis commands: evm-coinbase-transfer, evm-affected-addresses, evm-state-diff, and evm-traces.",
        breadcrumb_label: "Commands",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/coinbase-transfers",
        title: "Coinbase Transfers | mevlog",
        description: "Detecting a transaction's direct ETH payment to its block's coinbase.",
        breadcrumb_label: "Coinbase transfers",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/evm-rpc-revm-modes",
        title: "RPC & Revm Modes | mevlog",
        description: "The two --evm-trace modes: rpc (via debug_traceTransaction) and revm (local replay).",
        breadcrumb_label: "RPC & Revm modes",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/mcp",
        title: "MCP Server | mevlog",
        description: "Running the Model Context Protocol server (requires the mcp feature).",
        breadcrumb_label: "MCP Server",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/tui",
        title: "TUI Dashboard | mevlog",
        description: "The terminal UI dashboard (requires the tui feature).",
        breadcrumb_label: "TUI Dashboard",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/terms",
        title: "Privacy Policy & Terms | mevlog",
        description: "mevlog documentation privacy policy and terms of use.",
        breadcrumb_label: "Privacy & Terms",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.3",
        sitemap_changefreq: "yearly",
        faqs: &[],
    },
];
