use crate::content::Faq;

pub struct DocPage {
    pub path: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub breadcrumb_label: &'static str,
    pub last_updated_at: &'static str,
    pub sitemap_priority: &'static str,
    pub sitemap_changefreq: &'static str,
    pub faqs: &'static [Faq],
}

pub const DOC_PAGES: &[DocPage] = &[
    DocPage {
        path: "/docs/",
        title: "mevlog | EVM Transaction Monitoring & Querying CLI",
        description: "mevlog is an EVM transaction monitoring and querying CLI. It detects MEV, tracks smart contract storage, and resolves ENS names across any EVM-compatible chain.",
        breadcrumb_label: "Introduction",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.9",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/getting-started/installation",
        title: "Installation | mevlog",
        description: "Install mevlog and enable optional feature flags such as mcp and tui.",
        breadcrumb_label: "Installation",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/getting-started/quick-start",
        title: "Quick Start | mevlog",
        description: "Run your first mevlog query and index a block range.",
        breadcrumb_label: "Quick Start",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/getting-started/concepts",
        title: "Core Concepts | mevlog",
        description: "The indexing model, the signatures DB vs the per-chain transactions DB, and how chains are selected.",
        breadcrumb_label: "Core Concepts",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/configuration/config-file",
        title: "Config File | mevlog",
        description: "The ~/.mevlog/config.toml format and available options.",
        breadcrumb_label: "Config File",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/configuration/rpc-urls",
        title: "RPC URLs | mevlog",
        description: "Configuring RPC endpoints per chain, or auto-selecting them from ChainList.",
        breadcrumb_label: "RPC URLs",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/configuration/storage",
        title: "Caching & Storage | mevlog",
        description: "What lives under ~/.mevlog/: the SQLite databases, the cacache blob store, and the ENS and ERC20 symbol caches.",
        breadcrumb_label: "Caching & Storage",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/querying/query",
        title: "The query Command | mevlog",
        description: "query (alias q) collects transactions over a block range and indexes them into the local transactions DB.",
        breadcrumb_label: "The query Command",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/querying/sql",
        title: "SQL Query Layer | mevlog",
        description: "Running --sql against the indexed data, and the transactions, blocks, and logs table schemas.",
        breadcrumb_label: "SQL Query Layer",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/querying/u256-functions",
        title: "U256 SQL Functions | mevlog",
        description: "Custom SQLite functions for U256 BLOB columns: u256_sum, u256_mul, u256_add, u256_to_dec, erc20_to_real, and the format_ether, format_gwei, and format_usd display helpers.",
        breadcrumb_label: "U256 SQL Functions",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/querying/macros",
        title: "SQL Macros | mevlog",
        description: "Magic tokens expanded before a query runs: {LATEST_BLOCK()}, {NATIVE_TOKEN_PRICE()}, and {RESOLVE_ENS(\"name.eth\")}.",
        breadcrumb_label: "SQL Macros",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/querying/output",
        title: "Output Formats | mevlog",
        description: "The json and json-pretty formats and the QueryResponse envelope shape.",
        breadcrumb_label: "Output Formats",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/commands/transactions",
        title: "Transactions | mevlog",
        description: "The tx and tx-logs commands for inspecting a single transaction and its logs.",
        breadcrumb_label: "Transactions",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/commands/blocks",
        title: "Blocks | mevlog",
        description: "The block and block-txs commands for block metadata and a block's transactions.",
        breadcrumb_label: "Blocks",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/commands/evm-analysis",
        title: "EVM Analysis | mevlog",
        description: "Per-transaction analysis commands: evm-coinbase-transfer, evm-affected-addresses, evm-state-diff, and evm-traces.",
        breadcrumb_label: "EVM Analysis",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/commands/chains",
        title: "Chains | mevlog",
        description: "Discovering chains and their metadata: chains, chain-info, and debug-available.",
        breadcrumb_label: "Chains",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/commands/ens",
        title: "ENS | mevlog",
        description: "Resolving ENS names with ens-resolve and ens-lookup.",
        breadcrumb_label: "ENS",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/commands/database",
        title: "Database Management | mevlog",
        description: "Maintaining the local databases: update-db and db-info.",
        breadcrumb_label: "Database Management",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/integrations/mcp",
        title: "MCP Server | mevlog",
        description: "Running the Model Context Protocol server (requires the mcp feature).",
        breadcrumb_label: "MCP Server",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/integrations/tui",
        title: "TUI Dashboard | mevlog",
        description: "The terminal UI dashboard (requires the tui feature).",
        breadcrumb_label: "TUI Dashboard",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/reference/schema",
        title: "Database Schema | mevlog",
        description: "The signatures DB and per-chain transactions DB schemas, tables, and migrations.",
        breadcrumb_label: "Database Schema",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.6",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/reference/tracing",
        title: "EVM Tracing Modes | mevlog",
        description: "The two --evm-trace modes: rpc (via debug_traceTransaction) and revm (local replay).",
        breadcrumb_label: "EVM Tracing Modes",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.6",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/terms",
        title: "Privacy Policy & Terms | mevlog",
        description: "mevlog documentation privacy policy and terms of use.",
        breadcrumb_label: "Privacy & Terms",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.3",
        sitemap_changefreq: "yearly",
        faqs: &[],
    },
];
