use crate::content::Faq;

pub struct DocPage {
    pub path: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub breadcrumb_label: &'static str,
    pub last_updated_at: &'static str,
    pub sitemap_priority: &'static str,
    pub sitemap_changefreq: &'static str,
    pub faqs: &'static [Faq],
}

pub const DOC_PAGES: &[DocPage] = &[
    DocPage {
        path: "/docs/",
        title: "Documentation: Get Started with the EVM SQL CLI | mevlog-rs",
        description: "Documentation for the mevlog-rs CLI: index EVM blocks into local SQLite and query transactions, logs, and blocks with SQL. Install, core concepts, and command reference.",
        breadcrumb_label: "Introduction",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.9",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/quick-start",
        title: "Quick Start: Index & Query EVM Blocks | mevlog-rs",
        description: "Install mevlog, index an EVM block range into local SQLite, and run your first SQL query against on-chain transactions in just a few minutes.",
        breadcrumb_label: "Quick Start",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/core-concepts",
        title: "Core Concepts: Index, Store & Query | mevlog-rs",
        description: "How the mevlog index -> store -> query pipeline works, the signatures DB vs the per-chain transactions DB, and how EVM chains are selected.",
        breadcrumb_label: "Core concepts",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/indexing",
        title: "Indexing EVM Blocks into SQLite | mevlog-rs",
        description: "Cache EVM RPC data into a local SQLite database with mevlog: implicit indexing plus the index, reindex, and purge-db commands for managing block ranges.",
        breadcrumb_label: "Indexing",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/schema",
        title: "Database Schema: Transactions, Blocks & Logs | mevlog-rs",
        description: "The mevlog per-chain transactions database schema: the transactions, blocks, and logs tables, their columns, and U256 BLOB column types.",
        breadcrumb_label: "Schema",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/evm-sqlite-helpers",
        title: "SQLite Functions & Macros for EVM Data | mevlog-rs",
        description: "Custom SQLite functions for U256 BLOB columns (u256_sum, u256_mul, erc20_to_real), ETH/gwei/USD display helpers, and the LATEST_BLOCK, NATIVE_TOKEN_PRICE, and RESOLVE_ENS macros.",
        breadcrumb_label: "Functions & Macros",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.8",
        sitemap_changefreq: "weekly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/custom-tables",
        title: "Custom Log Tables from config.toml | mevlog-rs",
        description: "Define your own SQLite tables in ~/.mevlog/config.toml, auto-populate them from indexed EVM logs matching a topic0, and query them beside the built-in tables.",
        breadcrumb_label: "Custom Tables",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/sqlite-storage",
        title: "Storage Requirements & Disk Sizing | mevlog-rs",
        description: "How the local mevlog transactions database grows as you index EVM blocks, rough mainnet disk sizing, and checking usage with the db-info command.",
        breadcrumb_label: "Storage Requirements",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/evm-commands",
        title: "Per-Transaction EVM Analysis Commands | mevlog-rs",
        description: "Per-transaction EVM analysis with mevlog: evm-coinbase-transfer, evm-affected-addresses, evm-state-diff, and evm-traces for decoded call traces.",
        breadcrumb_label: "Commands",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/coinbase-transfers",
        title: "Detecting Coinbase Transfers & MEV Tips | mevlog-rs",
        description: "Detect a transaction's direct ETH payment to its block coinbase with mevlog, a common signal for MEV bundles and validator tips on EVM chains.",
        breadcrumb_label: "Coinbase transfers",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/evm-rpc-revm-modes",
        title: "RPC vs Revm Tracing Modes | mevlog-rs",
        description: "Compare the two mevlog --evm-trace modes: rpc via debug_traceTransaction and revm via local EVM replay, plus when to use each for tracing transactions.",
        breadcrumb_label: "RPC & Revm modes",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/cli-reference",
        title: "CLI Reference: All Commands & Options | mevlog-rs",
        description: "The complete mevlog command-line reference: every subcommand and option, generated directly from the binary's --help output.",
        breadcrumb_label: "CLI Reference",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/config",
        title: "config.toml Reference: RPC & Tables | mevlog-rs",
        description: "Configure mevlog via ~/.mevlog/config.toml: set custom per-chain RPC endpoints ([chains.<id>]) and define custom log tables ([tables.<name>]).",
        breadcrumb_label: "config.toml",
        last_updated_at: "2026-06-14",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/mcp",
        title: "MCP Server for AI Agents | mevlog-rs",
        description: "Run the mevlog Model Context Protocol (MCP) server to query EVM transactions from AI agents and LLM tools (requires the mcp feature).",
        breadcrumb_label: "MCP Server",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/tui",
        title: "TUI Dashboard for EVM Transactions | mevlog-rs",
        description: "Monitor live EVM transactions in mevlog's terminal UI dashboard, a real-time block and transaction explorer (requires the tui feature).",
        breadcrumb_label: "TUI Dashboard",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.7",
        sitemap_changefreq: "monthly",
        faqs: &[],
    },
    DocPage {
        path: "/docs/terms",
        title: "Privacy Policy & Terms of Use | mevlog-rs",
        description: "Privacy policy and terms of use for the mevlog documentation site and EVM transaction monitoring CLI.",
        breadcrumb_label: "Privacy & Terms",
        last_updated_at: "2026-06-13",
        sitemap_priority: "0.3",
        sitemap_changefreq: "yearly",
        faqs: &[],
    },
];
